### PR TITLE
Ft user post question #163002540

### PR DESCRIPTION
**Pull request by blairt001**
**What does this PR do?**
This Pull Request allows a user post a question on the platform.

**Description of Task to be completed?**
Create a questions page that allows a user to post a question on the site.
Responsive user interface

**How should this be manually tested?**
Clone this repository on your machine
CD into the project folder on your machine

run questions.html on the browser, chrome preferred
Click on questions button, then click ``Ask``.

**Pivotal Tracker story associated with this PR**
https://www.pivotaltracker.com/story/show/163002540

post-question

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
Hi. I think there's something wrong about the 'Technology' button,..though am not sure it's a button. The styling seems to be somehow off.

**Comment by SolomonMacharia** [comment]
And also on your PR, I suggest you include the PT story id too.

**Comment by Siffersari** [comment]
@blairt001 Kindly post a full screenshot if possible. I second @SolomonMacharia

**Comment by wachiranduati** [comment]
Also your commit message number 1 should be `start` not `started`
Other than that....nice design concept.. :)

**Comment by blairt001** [comment]
Great, let me work on them

**Comment by blairt001** [comment]
@SolomonMacharia , @Siffersari , @wachiranduati  thanks a bunch for the feedback. Though I decided to select a certain portion when capturing the screenshot but i have to obey your feedback. Thanks.

**Comment by blairt001** [comment]
> Hi. I think there's something wrong about the 'Technology' button,..though am not sure it's a button. The styling seems to be somehow off.

@SolomonMacharia  the PT story ID is the last on the link ``/163002540``

**Comment by blairt001** [comment]
> Also your commit message number 1 should be `start` not `started`
> Other than that....nice design concept.. :)

@wachiranduati  is what is the effect of using ``started`` instead of ``start`` , will it affect the project in any way? I am surprised have used it a lot. Thanks for the feedback.

**Pull request merged**
